version: '2'
services:
  template:
    container_name: template
    # put .env file in the project dir
    image: registry.cn-shanghai.aliyuncs.com/pardjs/template:0.0.1
    volumes:
      - "./logs:/var/log/nginx/log.log"
